---
- name: Test du déploiement des conteneurs
  hosts: all
  become: true
  tasks:
    - name: Vérifier que Docker est installé
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Vérifier que les conteneurs sont en cours d'exécution
      shell: "docker ps -f name={{ item }} --format '{{ .Names }}'"
      loop:
        - ubuntu_container
        - alpine_container
        - centos_container
        - debian_container
        - fedora_container
        - archlinux_container
        - opensuse_container
        - oraclelinux_container
        - freebsd_container
        - busybox_container
      register: container_status
      changed_when: false

    - name: Afficher les conteneurs en cours d'exécution
      debug:
        msg: "{{ container_status.results }}"
