---
# Tâches pour le rôle web-server

- name: Installer Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Démarrer Apache
  service:
    name: apache2
    state: started
