pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://your-git-repository-url.git'
            }
        }

        stage('Build Containers') {
            steps {
                sh 'docker-compose build'
            }
        }

        stage('Deploy with Ansible') {
            steps {
                sh 'ansible-playbook ansible/playbooks/deploy.yml'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'docker-compose exec web curl http://localhost:8080'
            }
        }
    }

    post {
        always {
            sh 'docker-compose down'
        }
    }
}
