---
- name: Configuration du serveur web
  hosts: webservers
  become: true
  tasks:
    - name: Mettre à jour le cache apt
      apt:
        update_cache: yes

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Copier le fichier de configuration Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Redémarrer Nginx

  handlers:
    - name: Redémarrer Nginx
      systemd:
        name: nginx
        state: restarted
