---
- name: Configuration de la base de données
  hosts: databases
  become: true
  tasks:
    - name: Mettre à jour le cache apt
      apt:
        update_cache: yes

    - name: Installer MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Démarrer et activer MySQL
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Sécuriser l'installation MySQL
      mysql_secure_installation:
        login_user: root
        login_password: ''
        new_password: 'votre_nouveau_mot_de_passe'
        remove_anonymous_user: yes
        disallow_root_login_remotely: yes
        remove_test_database: yes
        state: present
